os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

matrix:
  include:
  - os: linux
    rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
    - cargo test --verbose --no-default-features

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --no-default-features --features std
  - cargo doc

branches:
    except:
    - /.*(.tmp)$/
