os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

matrix:
  include:
  - name: fmt
    os: linux
    rust: stable
    before_script:
      - rustup component add rustfmt
    script:
      - cargo fmt --all -- --check
  - name: clippy
    os: linux
    rust: stable
    before_script:
      - rustup component add clippy
    script:
      - cargo clippy --all --tests
  - name: coverage
    os: linux
    rust: stable
    sudo: required
    addons: # needed for `cargo install cargo-travis`
      apt:
        packages:
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev
          - binutils-dev
          - cmake
        sources:
          - kalakris-cmake
    script:
      - cargo install cargo-travis --debug || echo "cargo-travis has been already installed"
      - mkdir target # fix for cargo-coveralls
      - cargo coveralls

  - name: wasi
    os: linux
    rust: stable
    install:
      - curl https://get.wasmer.io -sSfL | sh
    before_script:
      - rustup target add wasm32-wasi
    script:
      - cargo build --tests --target wasm32-wasi
    test:
      - cargo test --target wasm32-wasi -- -- --skip crypto::generichash::test::test_blake2b_vectors  \
            --skip crypto::hash::sha256::test::test_vectors_nist_short \
            --skip crypto::hash::sha256::test::test_vectors_nist_long \
            --skip crypto::hash::sha512::test::test_vectors_nist_short \
            --skip crypto::hash::sha512::test::test_vectors_nist_long \
            --skip crypto::sign::ed25519::test::test_vectors \
            --skip crypto::sign::ed25519::test::test_streaming_vectors \
            --skip utils::test::test_mlock_munlock


script:
  - cargo build --verbose
  - cargo test --verbose --all
  - cargo test --verbose --no-default-features --features std
  - cargo doc

branches:
    except:
    - /.*(.tmp)$/
